### ISSUE TITLE
How to change current choosing date when click KidSysco Month picker

### ISSUE THREAD

**Issue by sawnyi** [KidSysco/jquery-ui-month-picker#14]
Hi,

You month picker is really awesome.
But I have something wrong.
Month picker show current year when I first click that's true.
And month picker still showing current year when I click the next time.
That shouldn't be still showing current year, that should be showing my choosing year.
Please help me if you have some answer.

![month picker](https://cloud.githubusercontent.com/assets/14158887/9712325/e4e1e9b2-556f-11e5-9e61-44a77b7af2d7.PNG)

Best Regards,
Swan

**Comment by KidSysco** [comment]
I have not seen this behavior yet. Are you using supported versions of jQuery?

Can you post an example on jsFiddle?

The examples we have posted on jsFiddle do not show this behavior do they?

http://jsfiddle.net/kidsysco/JeZap/

Let me know.

**Comment by KidSysco** [comment]
It could also be your input format. Try this with the new MonthFormat option and see if it helps. It has been a while so i am closing this out. Let me know if you need anything else and we will open another issue.
