### ISSUE TITLE
Multiple Calendar window remains open on the page

### ISSUE THREAD

**Issue by togauravdaga** [KidSysco/jquery-ui-month-picker#19]
On a given page if you have multiple input fields using Month Picker, and user clicks on first input field followed by click on second input field then multiple windows of calendar remains open and it start to mess the page structure.  

This is reproducible on GitHub and also attaching a screenshot from my application to show this issue. 

![image](https://cloud.githubusercontent.com/assets/9852027/10441803/ae426cbc-7101-11e5-9d5f-a2d516b2fa3b.png)

Also from my application 
![image](https://cloud.githubusercontent.com/assets/9852027/10441839/10d272d2-7102-11e5-8a3d-8a623d3d92eb.png)

**Comment by KidSysco** [comment]
Yes I see. I am not sure where this re-appeared but we have no unit test for this. So we need to get one in place. I will keep you posted here in this thread.

**Comment by togauravdaga** [comment]
Thanks Ryan. I was trying to fix it by closing all jQuery dialog in _show
function. But that is band aid solution and decided to get your insight.

On Monday, October 12, 2015, Ryan Segura <notifications@github.com> wrote:

> Yes I see. I am not sure where this re-appeared but we have no unit test
> for this. So we need to get one in place. I will keep you posted here in
> this thread.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KidSysco/jquery-ui-month-picker/issues/19#issuecomment-147580803>
> .
>


-- 

*Thanks & Regards/ **सादर**,*
*Gaurav Daga*
*togauravdaga@gmail.com <togauravdaga@gmail.com> | +1.201.308.3242 | Web
Presence <http://goo.gl/lW0nh>  *
Do not follow where the path may lead. Go instead where there is no path
and leave a trail. - Harold R. McAlindon

**Comment by KidSysco** [comment]
Yea, we used to have this in there... 

$('.month-picker').hide();

But that doesn't quite do it anymore.

I think we might need to call Close() on each instance but I should talk with benjamin about it too. He will probably have a better idea.

**Comment by benjamin-albert** [comment]
I was hesitating about including code to workaround this issue on version 2.5, but I decided to leave this to version 2.6 were I'm going to suggest to make the menu a singleton (more about 2.6 coming up in it's own issue, I'm still researching and prototyping).

If you are using (or can upgrade to) version 2.5 you can workaround this by doing something like this:
<pre>
$(".selector").MonthPicker({
    OnBeforeMenuOpen: function() {
         $(".month-year-input").not(this).MonthPicker('Close');
    }
});
</pre>

**Comment by togauravdaga** [comment]
I'll try it and let you know results. Thanks for response.

On Monday, October 12, 2015, benjamin-albert <notifications@github.com>
wrote:

> I was hesitating about including code to workaround this issue on version
> 2.5, but I decided to leave this to version 2.6 were I'm going to suggest
> to make the menu a singleton (more about 2.6 coming up in it's own issue,
> I'm still researching and prototyping).
>
> If you are using (or can upgrade to) version 2.5 you can workaround this
> by doing something like this:
>
> $(".selector").MonthPicker({
>     OnBeforeMenuOpen: function() {
>          $(".month-year-input").not(this).MonthPicker('Close');
>     }
> });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KidSysco/jquery-ui-month-picker/issues/19#issuecomment-147584145>
> .
>


-- 

*Thanks & Regards/ **सादर**,*
*Gaurav Daga*
*togauravdaga@gmail.com <togauravdaga@gmail.com> | +1.201.308.3242 | Web
Presence <http://goo.gl/lW0nh>  *
Do not follow where the path may lead. Go instead where there is no path
and leave a trail. - Harold R. McAlindon

**Comment by benjamin-albert** [comment]
If anyone want's to add a built in workaround before I will finish 2.6 please add it and I'll merge the changes to my fork.

But like I said I'm expecting this problem to not be possible in version 2.6 (because there will be only one instance of the menu per page that is shared between the MonthPicker instances).

**Comment by togauravdaga** [comment]
Sure, I will give it a shot to close all windows based on css class and try
to push this change.

On Monday, October 12, 2015, benjamin-albert <notifications@github.com>
wrote:

> If anyone want's to add a built in workaround before I will finish 2.6
> please add it and I'll merge the changes to my fork.
>
> But like I said I'm expecting this problem to not be possible in version
> 2.6 (because there will be only one instance of the menu per page that is
> shared between the MonthPicker instances).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KidSysco/jquery-ui-month-picker/issues/19#issuecomment-147584995>
> .
>


-- 

*Thanks & Regards/ **सादर**,*
*Gaurav Daga*
*togauravdaga@gmail.com <togauravdaga@gmail.com> | +1.201.308.3242 | Web
Presence <http://goo.gl/lW0nh>  *
Do not follow where the path may lead. Go instead where there is no path
and leave a trail. - Harold R. McAlindon

**Comment by benjamin-albert** [comment]
I've created a pull request with an efficient solution for this issue. See <a href='https://github.com/benjamin-albert/jquery-ui-month-picker'>my fork</a>.

**Comment by KidSysco** [comment]
ok everything should be ready, minified with grunt, unit tests updated, and that latest fix appears to work great. 

Thanks to Gaurav for noticing the issue and reporting, thanks to Benjamin for a speedy fix!

Great work you guys!

Let me know if I missed anything.

r.

**Comment by togauravdaga** [comment]
I tested this today with jQuery 1.8 and jQuery 1.10 combination, and it works perfect.  Thanks for fixing it. 
:+1: 
Also, we changed layout from 3X4 to 4X3 and following line of code needed to be modified :

 for (var i = 0; i < 12; i++) {
       var $tr = !(i %  4) ? $('<tr />').appendTo($table) : $tr;
        $tr.append('<td><button class="button-' + (i + 1) + '" /></td>');
  }

**Comment by KidSysco** [comment]
That is awesome Gaurav! If you wanted to give back, you could add an option for layout for others and for yourself to use.... If you want.

;)
