### ISSUE TITLE
Clicks Re-Open the Menu

### ISSUE THREAD

**Issue by KidSysco** [KidSysco/jquery-ui-month-picker#22]
Upon clicking the input once, the menu opens. While open, if you click the input again, it closes then re-opens the menu.

This behavior does not exist when using the icon to open the menu.

I wouldn't have noticed or cared but it looks like Google put some attention to the HTML 5 Month Input type. There are new controls in the input that each respond to a click and pass along the hide/show events. SO if you try to use the spinners in the new Google Chrome HTML 5 input, it gets kinda flashy.

**Comment by benjamin-albert** [comment]
Yep, this is my bad. I'm on it.

**Comment by benjamin-albert** [comment]
Fixed, see #23

**Comment by KidSysco** [comment]
U da man Benjamin!
