### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by KidSysco** [KidSysco/jquery-ui-month-picker#25]
The new unit test system is so awesome, and there were some issues with the tests I wrote that still need to be resolved. These issues were compounded with the latest updates to the testing system.

The position test fails in the browser for 2 reasons...

1. Scrolling
The position tests scroll the window so that the input is in view. If we place the qUnit Test Output at the top of the page, then the position unit tests do not account for this and scroll the extra height. This is not an ideal solution because then anything we put at the top of the page will affect these tests that scroll the window to a certain location. My first thought to address this is to move the position test to the very top of the page as the first test, this way it is always in view and no scrolling is needed.

2. CSS
The right alignment is pushing the edges of the div up against the window boundry. There is some margin or padding or some CSS doing that.

I would like to get in to fix this and I don't want Benjamin to get in there and beat me to it! 

LOL!

This new test system is just soooo cool, it's like having a new toy to play with! So I want to handle this one here today.

WOOT!

**Comment by benjamin-albert** [comment]
"I would like to get in to fix this and I don't want Benjamin to get in there and beat me to it!"

LOL, I'll do my best to stay out of it :)

**Comment by KidSysco** [comment]
I'm having a blast doing this, this is such a better way to work!

**Comment by benjamin-albert** [comment]
I'm glad to hear that you like the new test system.

I've started working on tests for the MinMonth and MaxMonth options.

**Comment by KidSysco** [comment]
I just checked in, I made lots of adjustments to the test script so be sure to get the latest code. This was tons of fun to work in! I really like the updated QUnit too, I adjusted all of the asynch calls to conform to QUnit 2.0 which makes much more sense than previous versions.
