### ISSUE TITLE
Month Picker Calendar Instance Does not Open on Tabbing into Input Field.. Possible Enhancement? 

### ISSUE THREAD

**Issue by arpitshah29** [KidSysco/jquery-ui-month-picker#29]
Hello,

Is there any plans for putting in this functionality where the month picker opens up on tabbing into an input field?

I looked into the code and was able to figure closing of the month picker while tabbing out.

Issue was fixed by adding one more switch statement 

_keyDown: function() {
            var keyCode = $.ui.keyCode;
            switch (event.keyCode) {
                case keyCode.ENTER:
                    this._chooseMonth(new Date().getMonth() + 1);
                    this.Close();
                    break;
                case keyCode.ESCAPE:
                    this.Close();
                    break;
                case keyCode.TAB:
                    this.Close();
                    break;    
            }
        },

Version used : 2.5

**Comment by benjamin-albert** [comment]
I'm working on a fix for this. 

Stay tuned for a pull request assuming this doesn't involve any breaking changes.

**Comment by benjamin-albert** [comment]
I've opened a pull request with a fix for this issue (see #30).

I'm waiting for @KidSysco (the reop owner) to merge the change but feel free to grab <a href='https://github.com/benjamin-albert/jquery-ui-month-picker'>my version</a> of MonthPicker.js

If you are using a modified version of the plugin outside of a git repo I can give you instructions on how to implement this change, although I highly recommend that you use the up-to-date version which includes lots of new features and some minor bug fixes.

**Comment by benjamin-albert** [comment]
@KidSysco Merged the changes into his (the official repository) go ahead and download the update straight from <a href='https://github.com/KidSysco/jquery-ui-month-picker'>here</a>.

**Comment by KidSysco** [comment]
Closing this one out, feel free to open another issue if you run into anything strange. 

Thanks for reporting this to us!

**Comment by arpitshah29** [comment]
Thanks guys for quick turn around on this, Will keep you updated if I see any issues.

Appreciate the help!
