### ISSUE TITLE
manual entering input value gets reset after hitting enter

### ISSUE THREAD

**Issue by FaiqH** [KidSysco/jquery-ui-month-picker#32]
How do I have it so that if I were to enter the year manually it would not jump to the date on the calendar?

**Comment by benjamin-albert** [comment]
You can use the StartYear option.

Quoting the documentation:
StartYear

Type: Int
Default: Current Year
Sets the starting year in the month picker. This option will override all other start year behaviors.

Example:
    $("selector").MonthPicker({ StartYear: 2016 });

**Comment by FaiqH** [comment]
Thanks for the very quick reply!
I just found a solution to my situation.
I removed any returns on my enter key.
since I already have that key bound to the search button.

You have a great function built in - OnAfterMenuOpen. I used that as such:

```javascript
function datepicker() {
	$('.datepicker').MonthPicker({
		OnAfterMenuOpen: manualInput()
	});
}

function manInput() {
	$('.datepicker').on("keypress", function (e) {
		if (e.keyCode == 13) {
			return false; // prevent the button click vs. e.preventDefault();
		}
	});
}
```
Albeit it is a quick fix but it seems to do the job well.
Cheers

**Comment by benjamin-albert** [comment]
Oh, now I understand what your trying to do.

Stay tuned for a pull request that will make pressing enter selects the current month a little bit smarter (only if the user didn't change the date in the input field).

Thank you for pointing this out.

**Comment by benjamin-albert** [comment]
I've opened a pull request with a fix for this issue (see #30).

I'm waiting for @KidSysco (the reop owner) to merge the change, but feel free to grab <a href='https://github.com/benjamin-albert/jquery-ui-month-picker'>my version</a> of MonthPicker.js

If you are using a modified version of the plugin outside of a git repo I can give you instructions on how to implement this change, although I highly recommend that you use the up-to-date version which includes lots of new features and some minor bug fixes.

**Comment by FaiqH** [comment]
Thanks for the info!
I wasn't sure how to explain it.
but i found something else now as well.
Basically when a user will manually update the input box and hit enter due to the modification I used the action updates the calendar now. 
However, if I try to use the format function: MonthFormat: 'mm-yy' the input box will again display what's in the calendar rather than what the user entered. So i am trying to work around that as well.
I hope this input helps as well.

**Comment by benjamin-albert** [comment]
I'm sorry I don't quit understand whats going wrong.

If my update didn't solve this issue can you please attach your code and explain whats going wrong with it.

**Comment by FaiqH** [comment]
Sorry,
I will explain what I am trying to do:
If user enters date using keyboard and hits the enter key,
then the date in the input box does not change back to today date.

```javascript
function datepicker() {
		$('.date').MonthPicker(
		{
			Button: false,
			OnAfterMenuOpen: manualInput(),
            MonthFormat: 'mm-yy'
		});
}
function manualInput() {
		$('.date').on("keypress", function (e) {
			if (e.keyCode == 13) {
				return false; // prevent today's date
			}
		});
```

**Comment by benjamin-albert** [comment]
Did you try [my update](https://github.com/benjamin-albert/jquery-ui-month-picker/blob/master/MonthPicker.js) it should fix this issue.

I made it so that pressing enter will only override the value if the input field is empty.

Download and try my version and tell me if it fixed the issue.

**Comment by FaiqH** [comment]
works!

**Comment by KidSysco** [comment]
hi folks, thanks for working so well on this, everyone appreciates what you are doing! I am on holiday for the weekend, I should be able to get to this tomorrow or Monday. Thanks again!

**Comment by KidSysco** [comment]
forgot to close this issue.
