### ISSUE TITLE
The menu isn't positioned correctly (only in IE with jQuery versions 1.12.0 and 2.2.0)

### ISSUE THREAD

**Issue by benjamin-albert** [KidSysco/jquery-ui-month-picker#40]
Just as [you've described](https://github.com/KidSysco/jquery-ui-month-picker/issues/39#issuecomment-178152882) in #39 the month picker shows up as far below the input as you scrolled.

This bug only happens in **Internet Explorer** when you are using the latest versions of **jQuery (1.12.0 and 2.2.0)**.

Stay tuned as I dive into the details and figure out what's going wrong.

Until then I will update [index.html](https://github.com/KidSysco/jquery-ui-month-picker/blob/gh-pages/index.html) to use jQuery version 1.11.3 which doesn't seem to have this problem.

**Comment by benjamin-albert** [comment]
I just pushed  [index.html](https://github.com/KidSysco/jquery-ui-month-picker/blob/gh-pages/index.html) and looks like [everything is working fine](https://kidsysco.github.io/jquery-ui-month-picker/). 

I'll update you when I can find time to figure out what's going wrong.

**Comment by KidSysco** [comment]
OK it was the jQuery version. ok I see. Thanks for the help!

**Comment by KidSysco** [comment]
I wanted to be sure to document the issue for you. The issue only happens on the first click. That is the strange part. I looked at the code for a while and at the generated CSS. After the first click, everything works fine. I got as far as this article here. Not sure if it helps or not.

http://stackoverflow.com/questions/2834857/jquery-ui-datepicker-positioning-problem-when-scrolling-down-webpage

**Comment by benjamin-albert** [comment]
I've spent some time debugging this issue and this bug seems to occur deep within the [.offset()](https://github.com/jquery/jquery/blob/29370190605ed5ddf5d0371c6ad886a4a4b5e0f9/src/offset.js#L101) method of jQuery core.

Because I can't spend more time at home debugging this I've discussed the details in an issue I've opened at the jQuery core repo (jquery/jquery#2897).

Even though we've fixed the demo page I think it's important we (or the jQuery teem) address this issue before our users have to.

**Comment by benjamin-albert** [comment]
As mentioned in jquery/jquery#2897 it looks like we aren't the only ones affected by this bug.

I will leave this issue opened until the jQuery core tram [releases version 1.12.1/2.2.1](https://github.com/jquery/jquery/milestones/1.12.1/2.2.1).

Until then we will have to tell people to **use version 1.11.3**.

If someone will open an issue about this **after** we close this issue (**version 1.12.0 gets released**) we will tell them to **upgrade** to a new version.

I will also add comments that reference this issue in relevant places in the code.

**Comment by KidSysco** [comment]
ok I have updated the WIKI to show that 1.11.3 is the latest compatible
version.

I gotta get the ReadMe pointed to that here shortly.

r.

**Comment by KidSysco** [comment]
I also have Google open all day too. We can do the google hangouts chat too.

**Comment by benjamin-albert** [comment]
I really think we should add something like supported versions section in the Wiki.

When a user looks at browser and jQuery versions the main thing they are trying to do is answer the question _can I use this plugin?_

The user doesn't really care in what specific versions of jQuery we tested the plugin as long as we support there version.

I think we can say we support:
* jQuery version 1.9.1 and above.
* jQuery UI 1.9.2 and above.
* All modern browsers.
* A limited set of ancient browsers (IE 8-11).

@KidSysco Tell me what you think.

**Comment by KidSysco** [comment]
Yes, good idea. I am making an issue for this now so I dont forget.

**Comment by benjamin-albert** [comment]
Look like [jQuery released 1.12.1/2.2.1](http://blog.jquery.com/2016/02/22/jquery-1-12-1-and-2-2-1-released/) and the blog says that they fixed the problem with `.position()` in Internet Explorer.

@KidSysco Can you upgrade the jQuery version in the demo to [1.12.1](https://code.jquery.com) and make sure the problem with Internet Explorer was fixed.

**Comment by KidSysco** [comment]
I just checked and it looks good to me, that bug is fixed! I am going to push out the changes.

**Comment by benjamin-albert** [comment]
That's great, I'm going to close this issue now.
