### ISSUE TITLE
Inline Menu isn't working on IE8

### ISSUE THREAD

**Issue by donkung** [KidSysco/jquery-ui-month-picker#45]
When I open https://kidsysco.github.io/jquery-ui-month-picker/ in IE8.
The inline menu month picker isn't appear and there're alert "MonthPicker can only be called on text or month inputs"
This only happened in the actual IE8. The monthpicker in IE8 emulation on IE11 is still working.

**Comment by benjamin-albert** [comment]
Stay tuned while I check if I can find a real IE 8 anywhere around in my company.

**Comment by benjamin-albert** [comment]
Unfortunately the only place I can find a real Internet Explorer 8 is on one of our old production servers (where no one ever opens a web browser on, and there's no way the sysadmins will let me debug code on it).

I don't want to download a 3+ GB VM to my work computer.

@KidSysco Do you have a real IE 8 laying around where you can test (and debug this problem)?

**Comment by KidSysco** [comment]
Ben and I have been discussing. I am downloading a real IE 8 on windows xp vm right now. Hopefully we will know more shortly. I will keep you posted.

**Comment by KidSysco** [comment]
We just posted a fix for this now. 

@donkung Can you try it again and let us know what you see?

IE8 users should not use Https.

Here is a link for you...

http://kidsysco.github.io/jquery-ui-month-picker/

let us know!

**Comment by benjamin-albert** [comment]
I've opened an issue about the `$.inArray(void 0, ['text', 'month', void 0])` problem we were having in jQuery's repository, see: jQuery/jquery#2912

As @KidSysco has mentioned we've posted a workaround for this problem.

**Comment by donkung** [comment]
The inline menu month picker is working on the real IE8 now.

Thank you very much!

**Comment by benjamin-albert** [comment]
Thank you for opening an issue and helping us make this plugin better for everyone.

If you like this plugin please consider starring the repository, which will go a long way helping us get the plugin on [csnjs](https://github.com/cdnjs/cdnjs).
