### ISSUE TITLE
Provide a working demo when you download a zip/clone the repo

### ISSUE THREAD

**Issue by benjamin-albert** [KidSysco/jquery-ui-month-picker#46]
According to the [traffic graph](https://github.com/KidSysco/jquery-ui-month-picker/graphs/traffic) and [this comment](https://github.com/KidSysco/jquery-ui-month-picker/issues/35#issuecomment-168137979) in #35, it seems a lot of people are looking at the demo directory and expecting to find something useful and interesting, but instead they find two minified files that grunt generates that we use in the demo page.

What I think we should do is:

- [x]  Move the demo site [(gh-pages branch)](https://github.com/KidSysco/jquery-ui-month-picker/tree/gh-pages) to the demo directory.
- [x] Move the minified output to the `/demo` directory.
- [x] Make the demo page reference `MonthPicker.min.js` and `jquery.maskedinput.js` individually (instead of minifying them together).
- [x] Setup a grunt task which will automatically merge/deploy the demo dir to the [gh-pages branch](https://github.com/KidSysco/jquery-ui-month-picker/tree/gh-pages).

**Comment by benjamin-albert** [comment]
I'm going to move thing around a bit for this.

I'll discuss this in detail in the upcoming pull request.

**Comment by benjamin-albert** [comment]
You can see the new project layout in the [demo branch in my fork](https://github.com/benjamin-albert/jquery-ui-month-picker/tree/demo).

**Comment by KidSysco** [comment]
Very nice! Now THAT is a Demo folder with some good content in it!

I really like this layout! Great job, sorry I was not more help this week.

r.

**Comment by benjamin-albert** [comment]
I'm currently writing a pull request with the all the details.
