### ISSUE TITLE
Add the plugin to the bower registry

### ISSUE THREAD

**Issue by benjamin-albert** [KidSysco/jquery-ui-month-picker#48]
I'm still reading to see what this requires.

- [x] Add release tags to the repository.

**Comment by benjamin-albert** [comment]
I'm going to take the plugin out of beta so bower because I guess it's about time and I don't want bower to make trouble to try to install an older non-beta version.

I'm only going to add one tag right now which points to version 3.0 because the repo won't install correctly for most users in older versions (because we require a specific version of jQuery 1.9.1).

**Comment by benjamin-albert** [comment]
I think we'll be ready to add the plugin to the bower registry after I push a version bump to 3.0.0 and updates to `bower.json`.

The update to `bower.json` don't require the user to use jQuery 1.9.1, but will still install version 1.9.1 when installing for development (through `npm install`).

**Comment by benjamin-albert** [comment]
I'm glad to announce that the plugin is now in the [bower registry](http://bower.io/search/?q=jquery-ui-month-picker).

Try it yourself by (optional):

    mkdir bower_tryout
    cd bower_tryout
    bower init

And the most important part:

    bower install jquery-ui-month-picker

This command will download and install all of the plugin files and it's dependences (jQuery and jQuery-ui).

Now we just have to add this as an option in the installation section of the wiki.

**Comment by benjamin-albert** [comment]
I just updated the installation section of wiki.

@KidSysco Take a look and tell me what you think.

**Comment by KidSysco** [comment]
Wow, this is big news! Absolutely brilliant work Ben as usual! I can't wait to go and try it out!
