### ISSUE TITLE
Fix broken demo on JSFiddle

### ISSUE THREAD

**Issue by benjamin-albert** [KidSysco/jquery-ui-month-picker#49]
The demo on JSFiddle is missing one of the necessary CSS files and is not displaying the image icon (like it did before restructuring the project).

Please "pull" the changes from [this fork of the fiddle](http://jsfiddle.net/tft4zeww/2/).

**IMPORTANT:** Please Make sure you update the:
* External resources (added `test/test.css`).
* The CSS pane on the right.
* The fiddle's JavaScript pane (on the bottom).
* The Load type (in the JavaScript settings) to `onDomready`.

**Comment by KidSysco** [comment]
Done, let me know if you need anything else on this.
