### ISSUE TITLE
Selected month gets unselected after click in other place with jQuery-UI v1.11.4

### ISSUE THREAD

**Issue by aminix** [KidSysco/jquery-ui-month-picker#50]
Hi,
I am using the inline version of the monthpicker.
`<div class="monthly-input"></div>`
Im using jQuery-UI v1.11.4 with jQuery v2.1.4.
1 - I click on one of the months and it is colored as selected (it has the ui-state-active class). 
2 - As soon as I click outside the monthpicker the "ui-state-active" class is removed and the month looks unselected.
With jQuery-UI v1.9.2 works fine. Im using Chrome v48.0.

Any suggestions? Thank you.

**Comment by benjamin-albert** [comment]
Thank you very much for pointing this out.

I must admit that ever since we've released the beta of version 3.0 I've been impatiently waiting for someone to point out issues (that we couldn't find) in the jQuery UI Button hacks I've introduced in version 3.

But I'm surprised that this issue is occurring in a simple hack I've introduced long before version 3.

I can't wait to get home and look into this.

**Comment by aminix** [comment]
Haha okay, thank you! I did a quick patch locally by changing from <button> to <span> in the js and it works fine, but you might want to fix it appropriately :P 
Cheers.

**Comment by benjamin-albert** [comment]
I've tested this in Chrome, Firefox, and Safari and it seems that Chrome is the only browser that has this problem.

I have to admit it's nice to have an issue that only happens in a browser that is not Internet Explorer for a change :) (although I don't have a windows machine around to see if IE also has this problem).

**Comment by benjamin-albert** [comment]
I've just pushed a commit that should fix this issue.

I would appreciate it if you could check out the new version and tell
us if it fixes the problem for you.

**Comment by aminix** [comment]
It's fixed. Thanks!

**Comment by benjamin-albert** [comment]
Thank you for opening an issue and helping us make this plugin better for everyone.

If you like this plugin please consider starring the repository, which will go a long way helping us get the plugin on [cdnjs](https://github.com/cdnjs/cdnjs).
