### ISSUE TITLE
OnChange event from input doesn't fire

### ISSUE THREAD

**Issue by jwcurnalia** [KidSysco/jquery-ui-month-picker#52]
When you attach MonthPicker to an input with an OnChange event, the event does not fire after selecting a date.

**Comment by benjamin-albert** [comment]
According to [change - Event reference | MDN](https://developer.mozilla.org/en-US/docs/Web/Events/change):

The change event is fired for `<input>`, `<select>`, and `<textarea>` elements when a change to the element's **value is committed by the user**. Unlike the input event, the change event **is not** necessarily fired for each change to an element's value.

You can use our [OnAfterChooseMonthEvent](https://github.com/KidSysco/jquery-ui-month-picker/wiki/Events#onafterchoosemonth) instead.

**Comment by benjamin-albert** [comment]
Another important note the `change` and other _catch value change DOM events_ don't work in ancient browsers such as IE 8.

But our [OnAfterChooseMonth](https://github.com/KidSysco/jquery-ui-month-picker/wiki/Events#onafterchoosemonth) Event will work even in ancient browsers.

**Comment by KidSysco** [comment]
I see what Ben is saying here. His recommendation is to remove your onChange event and put the code for it into the OnAfterChooseMonth handler.
