### ISSUE TITLE
Which is the current version of your licence?

### ISSUE THREAD

**Issue by mediabakery** [KidSysco/jquery-ui-month-picker#54]
Hey Benjamin,

in your `package.json` you list **LGPL-2.1** as the current licence version. But in `MonthPicker.js` you mention **GNU Lesser General Public version 3.0 **.

What is the correct licence version?

Thanks a lot!
Sebastian

**Comment by benjamin-albert** [comment]
When I look in `MonthPicker.js` it looks like it says:

> GNU Lesser General Public version 3.0 

And then a few lines after that it says:

> http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt.

When I added the licence property to the `package.json` file I saw that LGPL-2.1 was the closest match.

@KidSysco Can you tell us what is the correct licence and update the appropriate file.

**Comment by benjamin-albert** [comment]
I see a lot of repositories that have a `LICENSE` file.
I think when you create a repository on GitHub you can create it with a `LICENSE` file.

I think we should add one to the repository.
@KidSysco Tell me what you think.

**Comment by KidSysco** [comment]
Ben and I have been chatting about this on Slack, I am going to change this out to the MIT license shortly.

**Comment by mediabakery** [comment]
@KidSysco sounds great! Thanks!

**Comment by KidSysco** [comment]
OK it should be ready to go, we decided on GPL 3.0, updated all references and added a LICENSE.txt file. Let us know if you find any other legal issues. Thanks!
