### ISSUE TITLE
Returning value as date?

### ISSUE THREAD

**Issue by bryner84** [KidSysco/jquery-ui-month-picker#55]
Is it possible to save the selection as a date value? I see this as returning the last day or first day of the selected month.  Right now the Request value of this field is something I have to parse out to convert to a date value to query a database for a given month.

I apologize if this isn't the correct place to pose the question.

**Comment by benjamin-albert** [comment]
You'r in the right place to ask questions like this which can help us improve our documentation and provide better examples for everyone.

If you want to get a [JavaScript Date](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date) object representing the selected value you can use the `$('.selector').MonthPicker('GetSelectedDate');` method on the client side.

But as far as I understand you are trying to query the database from the server side.

What you could do to make converting the selected value to a `data` or `time stamp` easier is use the
[AltField option](https://github.com/KidSysco/jquery-ui-month-picker/wiki/AltField-Option) and [AltFormat option](https://github.com/KidSysco/jquery-ui-month-picker/wiki/AltFormat-Option)s to display the selected value in one format and send the selected value in a different format (like a unix tome stamp) that you can easily convert to a `data` or `time stamp`on the server side.

See this [example fiddle](http://jsfiddle.net/nvrnkkbf/1/) for the AltField, AltFormat and MonthFormat options.

If you need help parsing the selected value in the server (after trying out the AltField/AltFromat options) we at least need to know language/framework your using on the server before we can help you

If your not using `node.js`, `PHP`, `Java`, `C#` or `PHP` on the server I wont be able to tell you how to convert the selected value sent to the server and then you'r probably better of asking a separate question on [stackoverflow](http://stackoverflow.com/).

**Comment by benjamin-albert** [comment]
I'm **really really** busy at work.
@KidSysco Can you add the [example fiddle](http://jsfiddle.net/nvrnkkbf/1/) I created to the deom page and fiddle?

**Comment by KidSysco** [comment]
Yeap, no problem!

**Comment by KidSysco** [comment]
I agree, this question is solved quite well with Ben's fiddle. I was able to modify it like this to get it to output the first day of the month in mm/dd/yy format. Nice touch with the unix format there Ben! Let us know if you have any other questions @bryner84.

Here is the code I used...

```
$('#monthField').MonthPicker({
  SelectedMonth: 'Jan, 2016',
	MonthFormat: 'M, yy', // Short month name, Full year.
  AltFormat: 'yy-dd-mm', // ODBC time stamp.
  AltField: '#serverValue' // Selector for hidden input.
});
```

**Comment by KidSysco** [comment]
Leaving this ticket open until I can update the demos with these examples, I will do standard american date format, Unix Format, and ODBC format.

**Comment by bryner84** [comment]
Thanks for the info.  Issue resolved.

**Comment by KidSysco** [comment]
Leaving this ticket open until I can update the demos with these examples, I will do standard american date format, Unix Format, and ODBC format.

**Comment by KidSysco** [comment]
demo updated, closing.
