### ISSUE TITLE
Setting MinMonth

### ISSUE THREAD

**Issue by bryner84** [KidSysco/jquery-ui-month-picker#56]
When specifying a date string for `MinMonth` it appears I need to add a day to get the result I'm looking for.

When I specify `MinMonth: new Date("2010-01-01")` I can select an option for Dec 2009.  I've worked around this by setting `MinMonth: new Date("2010-01-02")`.

This isn't a huge issue, but a FYI.

Thanks for writing this plugin.  Exactly what I needed.

**Comment by benjamin-albert** [comment]
If I understand correctly you'r not passing in a `String` you are passing in a `Date` object.

You don't need to wrap the `MinMonth` in a `Date` object you can just pass in the string (without the unnecessary day of month) like this:

    $('.selector').MonthPicker({
        // Must be in format specified in the MonthFormat option (this is the default format).
        MinMonth: '01/2010' 
     });

**Comment by bryner84** [comment]
I can do some formatting of my input, but I'm trying to leave things as native dates as this is how everything is saved in the database.

**Comment by KidSysco** [comment]
I grow so tired of date formatting back and forth between various systems. Whoever created that ODBC date format needs to be kicked in the shins. This is an interesting work around you have come up with here. I am glad it worked for you! Not sure it is worth changing any code for this but I can at least document the work around in the wiki.

**Comment by bryner84** [comment]
You and me both.  Feel free to close if you see fit.

**Comment by benjamin-albert** [comment]
I think it's worth noting that according to [Date - JavaScript | MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date).

> parsing of date strings with the Date constructor (and Date.parse, they are equivalent) is strongly discouraged due to browser differences and inconsistencies.

**Comment by benjamin-albert** [comment]
I also don't understand what you save by converting the date string into a JavaScript Date object.
You'r trying to avoid the two lines for code it takes to format the database date?

**Comment by benjamin-albert** [comment]
BTW I can't reproduce the issue with `new Date("2010-01-01")` becoming December 2009.

I guess this has something to do with browser inconsistencies or my timezone.
