### ISSUE TITLE
set SelectedMonth Options not update Alternative Field

### ISSUE THREAD

**Issue by tierrarara** [KidSysco/jquery-ui-month-picker#59]
Hi Guys,

After execute 

    $().MonthPicker('options', 'SelectedMonth', 'mystringmonth')

alternative field keep old value
I don't know if this is a issue o normal behavior
i try update _setSelectedMonth 

    _setSelectedMonth: function (_selMonth) {
            var month = _encodeMonth(this, _selMonth), _el = this.element;

            if (!month) {
                _el.val('');
                this._updateAlt(0, ''/*i´m not sure how to send empty value */);
            } else {
                var d = new Date(_toYear(month), month % 12, 1)
                _el.val(this._formatMonth(d));
                this._updateAlt(0, d);
            }

            this._ajustYear(this.options);
            this._showMonths();
        },

thansk for your attention

**Comment by KidSysco** [comment]
This looks like a bug to me. I will let Ben suggest a fix. 

Ben, when you are done, let me know if you want a test for it and I will do it.

**Comment by benjamin-albert** [comment]
Stay tuned for a pull request
