### ISSUE TITLE
Multi select month

### ISSUE THREAD

**Issue by lillo42** [KidSysco/jquery-ui-month-picker#66]
Hi, 
It's possible select multi month ?
If not, Can I try implement?

**Comment by KidSysco** [comment]
Wow, this would be a neat feature and it gets me thinking about lots more cool options that I never thought about before.

You are more than welcome to try to implement it yourself. Ben and I will review the code and make suggestions. Feel free to ask us for any help you may need.

**Comment by KidSysco** [comment]
Closing this one out for now, we have a pull request being reviewed for this one.
