### ISSUE TITLE
No buttun selection bubbles on multiple click

### ISSUE THREAD

**Issue by bsienn-khan** [KidSysco/jquery-ui-month-picker#71]
feature request.

Accidentally or intentionally clicking inside date input without button makes the date calendar bubbles and reset. Same for buttons options.
Sometimes due to faulty or sensitive mouse clicking this bubbling seems awkward.
Would be nice if the bubbling stops after first click if calendar is already visible.

**Comment by KidSysco** [comment]
Good input, I see what you mean. 

@benjamin-albert you can reproduce this behavior by visiting our demo page...

https://kidsysco.github.io/jquery-ui-month-picker/

Then clicking the text input box for No Button.

Once the menu appears, click the text input for No Button again.

You will see the menu disappear and re-appear.

I know you are working on the NPM package and this is not critical, so let me know what your schedule is like. I can probably take a look at this one eventually if needed.

Or we could see if @bsienn wants to take a crack at this. @bsienn, you could always issue a pull request. Setting up the dev environment for this project is a little tricky but I can always help you get started if you run into any problems. The biggest issue we have had with pull requests is ensuring all unit tests pass. Let me know if this is something you are interested in. You have been asking to help out here, so ensuring the plugin can pass all unit tests is probably the first thing you should learn about helping out in this repo. Eventually, we could probably have you add more unit tests too, this would help you get to learn the unit testing system! If you want to get started, have a look here...

https://github.com/KidSysco/jquery-ui-month-picker/wiki/Month-Picker-Development-Kit

Let me know if you have any questions!

Let me know how you want to move forward.

**Comment by bsienn-khan** [comment]
@KidSysco Seems like a plan. I'll start with unit testing and setup dev environment and start on this issue.
When everything gets on track and I get to the solution I'll try the PR. This might take some efforts but I'll manage it. Thanks

**Comment by benjamin-albert** [comment]
I'm sorry that I'm not as responsive as I usually am.

3 Months ago my dream of relocating to San Francisco came true.

1 Month ago this (and other open source projects I contribute to) had a huge impact on helping me get my dream job at this awesome startup called [Casetext](https://casetext.com/about).

Feb 23rd I moved into my dream apartment in the Mission Bay Area of San Francisco.

I am currently really busy:

1. Learning new things at my new job at Casetext during work hours.
2. Furnishing my new apartment on my free time.

Once this "marathon" is over I will definitely get around to the NPM and CDNJS module publishing and other things that need attention around this project.

I also want to write a blog post about how I probably wouldn't have gotten this amazing job (and apartment) without the open source contributions I had made to this and other projects.

**Comment by bsienn-khan** [comment]
Wow @benjamin-albert Really happy for you. And I wish you all the best in your life.  I hope to see you around the FOSS word.  Have a great time :)

**Comment by benjamin-albert** [comment]
@bsienn Thanks. You will definitely see me around this and hopefully other projects when this  "marathon" is over.

**Comment by KidSysco** [comment]
Great job BEN!!!! So Awesome and I am so happy for you! I know you will be an awesome asset to any team that picks you up.

No worries, you do your thing and I gotta find a way to get to S.F. one of these days to say hi now that you are in the US. I would really like to buy you a beer! LOL!

I was in Portland last weekend, lots of family there so you never know.

**Comment by benjamin-albert** [comment]
@KidSysco Sure! Feel free to reach out to me if you are in the Bay Area. 

LOL! beer sounds good!

**Comment by KidSysco** [comment]
@bsienn, sounds great! Let me know if you have any questions. I look forward to working with you!
