### ISSUE TITLE
How to disable some dates?

### ISSUE THREAD

**Issue by joselu1sc** [KidSysco/jquery-ui-month-picker#77]
Hello,

We found this date picker based on JQuery UI. So it is very cool component, but we did not found any option to disable some dates.

Actually, we need this feature to disable some taken dates of our calendar. Is this option available in new versions?

Best regards,

Jose Luis

**Comment by benjamin-albert** [comment]
When your saying dates I'm assuming you mean months.

There is no built-in option for this. However you can achieve this using events and extension points.

Here is a fiddle that demonstrates how to do this: http://jsfiddle.net/8x4nnvsj/4/

The fiddle is kind of a quick hack put together in #64 

The implementation shown in the fiddle will not work properly if there is more than one MonthPicker instance on the page but that can be fixed if necessary.

**Comment by joselu1sc** [comment]
That is great!

Thank you!
