### ISSUE TITLE
OnLoad event?

### ISSUE THREAD

**Issue by GreggOrdHume** [KidSysco/jquery-ui-month-picker#78]
Hello,

Thanks for the plugin, its saved me a massive amount of time and was easy to implement :)

I have a situation where i need an onLoad event. 

For the example below, I set a data attribute of the input when `OnBeforeMenuClose`. I want to set the data attribute when onLoad of the datePicker happens (because i have `selectedMonth:` set). Similar to ChartJs's event `afterDraw`.

So i would have something to this effect:
```
$('.js-datepicker').MonthPicker({ 
        ShowIcon: false,
        MonthFormat: 'MM yy',
        SelectedMonth: new Date(),
        OnBeforeMenuClose: function(event){
            $(this).attr('data-date',new Date(this.value).toLocaleDateString("en-GB"));
        },
        OnceLoaded: function(event){
            $(this).attr('data-date',new Date(this.value).toLocaleDateString("en-GB"));
        },
    });
```

I know in my case i could make a plan with the date. But i thought the OnLoad might be a useful event to have anyways :)

Thanks,
G

**Comment by benjamin-albert** [comment]
@GreggOrdHume Use the jQuery UI widget `create` event.

Also note you should:
* bind a `change` event to the filed to support the user manually changing the value in the input field.
* use the [GetSelectedDate](https://github.com/KidSysco/jquery-ui-month-picker/wiki/API-Methods) method (instead of `this.value`) which will return `null` if the user manually typed in an invalid month.

Example:
```js
$(".js-datepicker")
.change(updateAttr)
.MonthPicker({
  ShowIcon: false,
  MonthFormat: "MM yy",
  SelectedMonth: new Date(),
  create: updateAttr,
  OnAfterChooseMonth: updateAttr
});


function updateAttr() {
  var date = $(this).MonthPicker("GetSelectedDate");
  $(this).attr("data-date", date ? date.toLocaleDateString("en-GB") : "null");
}
```

Example fiddle: http://jsfiddle.net/ev8kk1rv/7/

**Comment by benjamin-albert** [comment]
Ideally we should have something similar to the [AltField option](https://github.com/KidSysco/jquery-ui-month-picker/wiki/AltField-Option) that would make something like this simple.

**Comment by GreggOrdHume** [comment]
Thanks Benjamin! The example above is perfect.

`create:` is exactly what i need.

The `AltField` is close but essentially I am only setting the data attribute so i can grab it later and put it into a variable. `create:` and `onAfterChooseMonth:` will allow me to skip the whole data-attribute approach and set the variable inside those events.

Many many thanks :)
