### ISSUE TITLE
Error with jQuery jQuery 3.21./jQueryUI 1.12.1

### ISSUE THREAD

**Issue by lcfink** [KidSysco/jquery-ui-month-picker#80]
Picker loads with month-picker-previous and month-picker-next buttons disabled.

The problem seems to be that _value is null (not false, but falsie) on input.
The check if (_btnWidget.option('disabled') !== _value) is true, so _btnWidget.option('disabled', _value) executes, which disables the buttons.

An easy fix is to validate _value:
_value = !(!_value);

**Comment by KidSysco** [comment]
Good find, we should probably try to support jQuery 3.x sometime soon.

**Comment by lcfink** [comment]
If I may say, I've tested pretty thoroughly in my applications, and plan to deploy your month picker running in 3.x, with my manual fix. That's the only issue I found.

**Comment by KidSysco** [comment]
OK great, I was going to say that @ComiR at https://github.com/KidSysco/jquery-ui-month-picker/pull/79 found another way to address this issue. It passed all of our unit tests too. I should probably merge that up soon and it should address this issue. Thanks for chiming in!

**Comment by benjamin-albert** [comment]
Welcome to GitHub @lcfink 

Thank you for opening an issue and expressing interest in jQuery UI 1.12 and jQuery 3 support.

Supporting jQuery UI 1.12 is being discussed in #73 which includes the fix you're proposing and other important fixes which address the visual glitches.

Let's continue the discussion around supporting jQuery UI 1.12 and jQuery 3 in #73
