### ISSUE TITLE
show years first?

### ISSUE THREAD

**Issue by eliteproxy7** [KidSysco/jquery-ui-month-picker#81]
is it possible for the users to have to select a year first before the month?

right now it opens to current year, but I would like for the users to see the years first

**Comment by KidSysco** [comment]
That is an interesting idea. 

The call to Open the menu will always reset the menu back to months. So you will probably need to show the years, after Open is called.

I suppose I would first try to implement the OnAfterMenuOpen event...
https://github.com/KidSysco/jquery-ui-month-picker/wiki/Events#onaftermenuopen

Then I would find a way to call _showYears at line 930 and I suppose that should probably be an option. 

If you are not comfortable adding an option to a jQuery UI plugin, then I might just find a way to click() that button from the same event handler. Perhaps something like this...

```
var _picker = $('#MyMonthPicker').MonthPicker({
        StartYear: 2027,
        OnAfterMenuOpen: function () {
            $('.month-picker-title a', _pickerMenu).trigger($.Event('click'));
        }
    });

var _pickerMenu = $('#MonthPicker_MyMonthPicker');

```
