### ISSUE TITLE
Fill in 2 hidden input field

### ISSUE THREAD

**Issue by aragorn-be** [KidSysco/jquery-ui-month-picker#82]
Hello,
I'm a newbie, so sorry if my question sounds stupid... ;-)
I would like to use the AltFormat and AltField feature. This feature is designed to fill in a single INPUT field.
However I would like to fill in 2 hidden INPUT fields after picking a month: the first one named "month" and the second one named "year".
How can I do this with that package?
Thanks for your help or advise.

**Comment by KidSysco** [comment]
It just takes any jQuery selector. So use this...

$('.selector').MonthPicker({ AltField: '#field, #field2' });

I just tested it out real quick and it works, see below...

http://jsfiddle.net/kidsysco/bsxzd4kq/

**Comment by KidSysco** [comment]
It seems to work with both AltField and AltFormat at that same fiddle.

$('.Default').MonthPicker({ AltField: '#MyFirstField, #MySecondField', AltFormat: 'yy-mm' });

**Comment by aragorn-be** [comment]
Hi,
Thanks a lot for the quick reply. I appreciate... :-)
I've tested your code and indeed it updates 2 differents fields.
However the content of these 2 fields are exactly the same... What I would like to get is: one (hidden) field with the year (eg. 2018) and the other (hidden) field with the month (eg. 3).
So when I click on the "Submit" button of the form afterwards (GET method) I can create a URL like "http://mydomain.com/mypage.php?month=3&year=2018".

**Comment by KidSysco** [comment]
If that is the case, then I would not use AltField or AltFormat. I would just use the API calls to get the year and the month like this...

$('.selector').MonthPicker('GetSelectedMonth') 
Returns only the month portion of the selected date as an integer. Returns NaN if there is no valid date.

$('.selector').MonthPicker('GetSelectedYear') 
Returns only the year portion of the selected date as an integer. Returns NaN if there is no valid date.

And I would have to use those API calls from an event... I suppose the OnAfterCHooseMonth or OnAfterMenuClose events would work...

https://github.com/KidSysco/jquery-ui-month-picker/wiki/Events#onafterchoosemonth

https://github.com/KidSysco/jquery-ui-month-picker/wiki/Events#onaftermenuclose

Every time the user makes a choice, the menu will close causing the OnAfterMenuClose event to fire. From there, Get the Selected Month and Year to build your URL.

**Comment by aragorn-be** [comment]
Once again, I appreciate your dedication to help me.
However as I'm an newbie, this sounds as "chinese" for me... ;-) Sorry for this!
Could you please provide a practical example in Fiddle?

**Comment by aragorn-be** [comment]
Hi again...
Please forget my last request... I finally spent some time to adapt my PHP code to use one single field (concatenation of year/month) i.s.o 2 different ones. So your package is now adapted to that approach.
Thanks again for your help... I'm gonna close this issue. :-)
