### ISSUE TITLE
Autoclose Support

### ISSUE THREAD

**Issue by nuclearsiloman** [KidSysco/jquery-ui-month-picker#83]
Does this have autoclose support like datepicker?

**Comment by KidSysco** [comment]
I am not sure what you mean. Can you provide a link to the documentation or some sort of example of what you are looking for?

**Comment by nuclearsiloman** [comment]
Sure.  If you go here:  http://bootstrap-datepicker.readthedocs.io/en/latest/options.html#autoclose
The second section is Autoclose; setting that closes the calendar as soon as a date is picked, so the user doesn't have to click off of it to close

**Comment by KidSysco** [comment]
If I go to the demo page for the month picker...

https://kidsysco.github.io/jquery-ui-month-picker/

And I click on any one of those, then I choose a date, the month picker hides/closes.

So the month picker will close upon clicking anywhere on the page, and it will also close upon selecting a date.

Are you asking for a way to shut that off?

If so, no I don't think there is a way to turn off that behavior at this time.

Auto Close is always on in this plugin.

**Comment by KidSysco** [comment]
However, you could use an inline month picker to achieve the same effect I suppose.

https://github.com/KidSysco/jquery-ui-month-picker/wiki/Inline-Menu

See the Inline Menu Demonstration on the demo page for month picker too. It will never hide, it will always show inline. That is about as close as we can get to turning off the auto hide behavior you are looking for.

**Comment by nuclearsiloman** [comment]
Odd.  When I click a month, it doesn't close.

**Comment by KidSysco** [comment]
ok, well perhaps you have found a bug.

Can you share a fiddle? See if we can reproduce the behavior?

What browser? OS?

**Comment by nuclearsiloman** [comment]
I think there is a conflict with something else in the page.  If I move it to a simple page without all the clutter it works fine.  Nothing shows in the console, so I guess I'll just add one thing at a time until it doesn't close on its own.  Thanks for your help.

**Comment by KidSysco** [comment]
It just calls .hide(), to hide the menu. Which should just change a css class on the element named hide, probably just setting the display to none. (line 615)

However, if you are using an animation, then it works a bit different. You could also try turning off the close animation and see if that helps.

https://github.com/KidSysco/jquery-ui-month-picker/wiki/Animation-Option

Let us know how it goes!

**Comment by KidSysco** [comment]
How is this one going @nuclearsiloman?

Did you figure out what was causing the failure?

Sure would be interesting to know.
