### ISSUE TITLE
Add support for Week/Year picker

### ISSUE THREAD

**Issue by krisred** [KidSysco/jquery-ui-month-picker#84]
Hello,
Thanks for creating this awesome picker, it would be great to have an option to select week/year
May have a tab on tab - default to month | week
When in month it would show months, when in week - it would show week numbers 01 thru 52
so user selects week 2 in 2018 the it would input 02/2018

Kris

**Comment by benjamin-albert** [comment]
This repo is specifically for choosing months. Feel free to fork the repo and make a version that allows choosing weeks.

**Comment by KidSysco** [comment]
I agree. This is too big of a requirement for this plugin. This idea deserves it's own plugin.
