### ISSUE TITLE
Get the selected year

### ISSUE THREAD

**Issue by QuoSijyro** [KidSysco/jquery-ui-month-picker#85]
Hello,
I really like your MonthPicker and I'm using it for a school project.

But i have some troubble to get the year I just selected when i click on a specific year
If i use:
```
OnAfterChooseYear: function () {
            var date = $('#datePicker').MonthPicker('GetSelectedYear');
            console.log(date);
}
```
It's going to show me the last year where I just choosed a month.

For exemple, if I click on the June month of 2018 and then i click on 2015, it's going to show me 2018 year, and not the 2015 one.

If you have something to help me with it. Thanks.

Best regards, Sijyro

**Comment by KidSysco** [comment]
Hello @QuoSijyro,

Th method for GetSelectedYear gets the year that is currently selected in the text box, see this example I put together with your code...

http://jsfiddle.net/kidsysco/bsxzd4kq/

The OnAfterChooseYear event handler fires after clicking a year button, but the year is not really selected until both a month and a year are chosen, the menu closes, then both show in the text box. 

So in your example, notice that it is always showing the year that is in the text box.

Instead, maybe try using the OnAfterMenuClose event handler. It should work better but will only fire when the menu closes.

Let me know if you have any other questions.

**Comment by QuoSijyro** [comment]
Thank you for your fast reply.

I'm actually using the MonthPicker as Inline Menu,
here is my code http://jsfiddle.net/bsxzd4kq/13/

If I understood well, you are saying that I'm able to take the year value from the textbox.
But I'm not using textbox here.

Is there is a way to get the year without having to select a month precisly ?
Or why not, I was thinking about automatically select the first month in the OnAfterChooseYear event, maybe if I select a month with code I'm able to take the year from this month selected right ?

Thanks for your help.

**Comment by KidSysco** [comment]
There is no AIP support for this, but you could add it in.

You need to call _setSelectedMonth which is only available internally to the plugin. So you will need to create a public facade for it around line 482, like we did for the other publicly accessible functions. Call _setSelectedMonth from that public method, then call the public method from OnAfterChooseYear followed by a call to GetSelectedYear. Then yes, I think that might work.

Let us know how that goes.

**Comment by benjamin-albert** [comment]
Another option that doesn't require forking the code base is accessing the internal `_pickerYear` property.

See example fiddle for this: http://jsfiddle.net/ks5jowep/3/

This use case is not supported and might break in future releases.

**Comment by KidSysco** [comment]
That is a really good idea considering how @QuoSijyro wants to use the plugin.

**Comment by QuoSijyro** [comment]
Thanks for your replies, creating a public facade for what I want could be nice @KidSysco
But I don't really know a lot about JavaScript so I think I'm going to use the @benjamin-albert technique.

If I have more time to do it I'll add it in the code like you said @KidSysco

Thanks a lot, Sijyro.
