### ISSUE TITLE
Jquery on Change

### ISSUE THREAD

**Issue by allipierre** [KidSysco/jquery-ui-month-picker#86]
Hi,
Jquery on change (https://api.jquery.com/change/) doest not works when input field change

Regards

Pierre

**Comment by KidSysco** [comment]
Hi @allipierre,
If you read through the docs you sent, you will notice this line...

```
Changing the value of an input element using JavaScript, using .val() for example, won't fire the event.
```

This script works by changing the value of the text box using script. So you are correct. It will not fire the change event.

If you need to tie in an event, you should use one of the events built in to the Month Picker...

https://github.com/KidSysco/jquery-ui-month-picker/wiki/Events

Try using the OnAfterMenuClosed event to detect changes to the input box instead.

Let us know how that goes.

**Comment by allipierre** [comment]
When
try that it defekt the change 
$('#P105_ANFAN_UPDATED_ON').MonthPicker({
    OnAfterMenuClose: function() {
   }
});


Is there a way to use the jquery change to use that event ?

**Comment by KidSysco** [comment]
Just call the change event yourself from OnAfterMenuClose.

$(".Default").trigger("change");

See fiddle below.

http://jsfiddle.net/kidsysco/bsxzd4kq/

**Comment by allipierre** [comment]
Thanks works

**Comment by KidSysco** [comment]
woot!
