### ISSUE TITLE
MonthPicker Error: The jQuery UI button and datepicker plug-ins must be loaded.

### ISSUE THREAD

**Issue by Gokulakannanaj** [KidSysco/jquery-ui-month-picker#94]
Hi,

Getting following error while running

**MonthPicker Error: The jQuery UI button and datepicker plug-ins must be loaded.**

I attached all the files But still getting Above error. Here I don't know what am i  missing?

Thanks.

**Comment by KidSysco** [comment]
You should try to make sure you have jQuery UI installed to the project first.
