### ISSUE TITLE
Setting date manually.

### ISSUE THREAD

**Issue by flaczkiDomowe** [KidSysco/jquery-ui-month-picker#96]
Hello. How can I set some text/date in input manually? Is clicking the button the only way to do it? I read documentation but I couldn't find it. My problem actually is that in event onAfterChooseMonth i do check selectedDate and if it is bad for x reason, I can't prevent it to set anyways.

**Comment by KidSysco** [comment]
Look at the demo.

https://kidsysco.github.io/jquery-ui-month-picker/

The second month picker listed on the page shows how to create an input with no button, you can demo how it works there too.

TO show errors for bad dates, see the wiki.

https://github.com/KidSysco/jquery-ui-month-picker/wiki/API-Methods

```
$('.selector').val()
Use jQuery .val() to get the input without any date validation.

$('.selector').MonthPicker('Validate')
Validates the selected month/year and returns the selected value as a Date object if it is a valid date. Returns null if there is no valid date, displays an error message if the message is specified, focuses and selects the violating text. (Added in version 2.4)
```

**Comment by flaczkiDomowe** [comment]
Thanks 👍
